obj-y += gx_scroll_thumb_create.o
obj-y += gx_scroll_thumb_draw.o
obj-y += gx_scroll_thumb_event_process.o
obj-y += gx_scroll_thumb_shift_limit.o
obj-y += gxe_scroll_thumb_create.o
obj-y += gxe_scroll_thumb_event_process.o
