obj-y += tx_mutex_cleanup.o
obj-y += tx_mutex_create.o
obj-y += tx_mutex_delete.o
obj-y += tx_mutex_get.o
obj-y += tx_mutex_info_get.o
obj-y += tx_mutex_initialize.o
obj-y += tx_mutex_performance_info_get.o
obj-y += tx_mutex_performance_system_info_get.o
obj-y += tx_mutex_prioritize.o
obj-y += tx_mutex_priority_change.o
obj-y += tx_mutex_put.o

obj-y += txe_mutex_create.o
obj-y += txe_mutex_delete.o
obj-y += txe_mutex_get.o
obj-y += txe_mutex_info_get.o
obj-y += txe_mutex_prioritize.o
obj-y += txe_mutex_put.o
