ifeq ($(Platform),rockchip)
-include config/build.rv11xx.version
-include config/build.config.rv11xx
else ifeq ($(Platform),nxp)
-include config/build.imx6ull.version
-include config/build.config.imx6ull
else
-include config/build.host.version
-include config/build.config.host
endif
