obj-y += children_layouter_builtins.o
obj-y += children_layouter_default.o
obj-y += children_layouter_parser.o
obj-y += self_layouter_builtins.o
obj-y += self_layouter_default.o
obj-y += self_layouter_menu.o
obj-y += self_layouter_parser.o
