obj-y += lv_draw_vglite_arc.o
obj-y += lv_draw_vglite_blend.o
obj-y += lv_draw_vglite_line.o
obj-y += lv_draw_vglite_rect.o
obj-y += lv_draw_vglite.o
obj-y += lv_vglite_buf.o
obj-y += lv_vglite_utils.o
