obj-y += gx_accordion_menu_create.o
obj-y += gx_accordion_menu_draw.o
obj-y += gx_accordion_menu_event_process.o
obj-y += gx_accordion_menu_position.o
obj-y += gxe_accordion_menu_create.o
obj-y += gxe_accordion_menu_event_process.o
obj-y += gxe_accordion_menu_position.o
