obj-y += tx_event_flags_cleanup.o
obj-y += tx_event_flags_create.o
obj-y += tx_event_flags_delete.o
obj-y += tx_event_flags_get.o
obj-y += tx_event_flags_info_get.o
obj-y += tx_event_flags_initialize.o
obj-y += tx_event_flags_performance_info_get.o
obj-y += tx_event_flags_performance_system_info_get.o
obj-y += tx_event_flags_set.o
obj-y += tx_event_flags_set_notify.o

obj-y += txe_event_flags_create.o
obj-y += txe_event_flags_delete.o
obj-y += txe_event_flags_get.o
obj-y += txe_event_flags_info_get.o
obj-y += txe_event_flags_set.o
obj-y += txe_event_flags_set_notify.o
