obj-$(CONFIG_ROCKCHIP_RV11XX_LIBDRM) += rv11xx_unittest_libdrm_display_example.o
obj-$(CONFIG_ROCKCHIP_RV11XX_CAMERA_LIBDRM) += rv11xx_unittest_camera_libdrm_display_example.o

obj-y += rv11xx_unittest.o
