obj-y += sigslot_unittest.o
obj-$(CONFIG_HOST_SIGNAL_SLOTS) += host_unittest_signal_slots_example.o
obj-$(CONFIG_HOST_SIGSLOT_THREADED_PRODUCER_CONSUMER) += host_unittest_sigslot_threaded_producer_consumer_example.o
