obj-y += blend/

obj-y += lv_draw_sw_arc.o
obj-y += lv_draw_sw_bg_img.o
obj-y += lv_draw_sw_border.o
obj-y += lv_draw_sw_box_shadow.o
obj-y += lv_draw_sw_fill.o
obj-y += lv_draw_sw_gradient.o
obj-y += lv_draw_sw_img.o
obj-y += lv_draw_sw_letter.o
obj-y += lv_draw_sw_line.o
obj-y += lv_draw_sw_mask_rect.o
obj-y += lv_draw_sw_mask.o
obj-y += lv_draw_sw_transform.o
obj-y += lv_draw_sw_triangle.o
obj-y += lv_draw_sw.o
