obj-$(CONFIG_HOST_UNITTEST_RTSP) += rtsp/
obj-$(CONFIG_HOST_UNITTEST_LIBDRM) += libdrm/
obj-$(CONFIG_HOST_UNITTEST_LIVE555) += live555/
obj-$(CONFIG_HOST_UNITTEST_SIGSLOT) += signalslot/

obj-y += host_unittest.o
