obj-$(CONFIG_HOST_UNITTEST_BOOST) += boost/
obj-$(CONFIG_HOST_UNITTEST_QTCORE) += qtcore/
obj-$(CONFIG_HOST_UNITTEST_LIBDRM) += libdrm/
obj-$(CONFIG_HOST_UNITTEST_SIGSLOT) += signalslot/

obj-y += host_unittest.o
