obj-y += lcd_mono.o
obj-y += lcd_mem_bgr565.o
obj-y += lcd_mem_bgr888.o
obj-y += lcd_mem_bgra8888.o
obj-y += lcd_mem_rgb565.o
obj-y += lcd_mem_rgb888.o
obj-y += lcd_mem_rgba8888.o
obj-y += lcd_mem_special.o
