obj-y += tx_block_allocate.o
obj-y += tx_block_pool_cleanup.o
obj-y += tx_block_pool_create.o
obj-y += tx_block_pool_delete.o
obj-y += tx_block_pool_info_get.o
obj-y += tx_block_pool_initialize.o
obj-y += tx_block_pool_performance_info_get.o
obj-y += tx_block_pool_performance_system_info_get.o
obj-y += tx_block_pool_prioritize.o
obj-y += tx_block_release.o

obj-y += txe_block_allocate.o
obj-y += txe_block_pool_create.o
obj-y += txe_block_pool_delete.o
obj-y += txe_block_pool_info_get.o
obj-y += txe_block_pool_prioritize.o
obj-y += txe_block_release.o
