obj-y += tx_byte_allocate.o
obj-y += tx_byte_pool_cleanup.o
obj-y += tx_byte_pool_create.o
obj-y += tx_byte_pool_delete.o
obj-y += tx_byte_pool_info_get.o
obj-y += tx_byte_pool_initialize.o
obj-y += tx_byte_pool_performance_info_get.o
obj-y += tx_byte_pool_performance_system_info_get.o
obj-y += tx_byte_pool_prioritize.o
obj-y += tx_byte_pool_search.o
obj-y += tx_byte_release.o

obj-y += txe_byte_allocate.o
obj-y += txe_byte_pool_create.o
obj-y += txe_byte_pool_delete.o
obj-y += txe_byte_pool_info_get.o
obj-y += txe_byte_pool_prioritize.o
obj-y += txe_byte_release.o
