
obj-y += wash_cycle.o
obj-y += water_level.o
obj-y += temperature.o
obj-y += mode_select.o
obj-y += guix_washing_machine.o
obj-y += demo_guix_washing_machine_resources.o
obj-y += demo_guix_washing_machine_specifications.o
