obj-y += demo_flex_layout_ctrl_pad.o
obj-y += demo_flex_layout_flex_loader.o
obj-y += demo_flex_layout_main.o
obj-y += demo_flex_layout_view_child_node.o
obj-y += demo_flex_layout_view_ctrl_pad.o
obj-y += demo_flex_layout_view.o
