obj-y += gx_screen_stack_create.o
obj-y += gx_screen_stack_pop.o
obj-y += gx_screen_stack_push.o
obj-y += gx_screen_stack_reset.o
obj-y += gxe_screen_stack_create.o
obj-y += gxe_screen_stack_pop.o
obj-y += gxe_screen_stack_push.o
obj-y += gxe_screen_stack_reset.o
