obj-y += gx_text_input_cursor_blink_interval_set.o
obj-y += gx_text_input_cursor_dirty_rectangle_get.o
obj-y += gx_text_input_cursor_draw.o
obj-y += gx_text_input_cursor_height_set.o
obj-y += gx_text_input_cursor_width_set.o
obj-y += gxe_text_input_cursor_blink_interval_set.o
obj-y += gxe_text_input_cursor_height_set.o
obj-y += gxe_text_input_cursor_width_set.o
