obj-y += block/
obj-y += byte/
obj-y += event/
obj-y += initialize/
obj-y += mutex/
obj-y += queue/
obj-y += semaphore/
obj-y += thread/
obj-y += time/
obj-y += timer/
obj-y += trace/

obj-y += tx_misra.o
