obj-$(CONFIG_AZURE_GUIX_SIMPLE) += simple/
obj-$(CONFIG_AZURE_GUIX_SPRITE) += sprite/
obj-$(CONFIG_AZURE_GUIX_SHAPES) += shapes/
obj-$(CONFIG_AZURE_GUIX_MEDICAL) += medical/
obj-$(CONFIG_AZURE_GUIX_KEYBOARD) += keyboard/
obj-$(CONFIG_AZURE_GUIX_INDUSTRIAL) += industrial/
obj-$(CONFIG_AZURE_GUIX_CALCULATOR) += calculator/
obj-$(CONFIG_AZURE_GUIX_THERMOSTAT) += thermostat/
obj-$(CONFIG_AZURE_GUIX_SMART_WATCH) += smart_watch/
obj-$(CONFIG_AZURE_GUIX_WIDGET_TYPES) += widget_types/
obj-$(CONFIG_AZURE_GUIX_WASHING_MACHINE) += washing_machine/
obj-$(CONFIG_AZURE_GUIX_HOME_AUTOMATION) += home_automation/
obj-$(CONFIG_AZURE_GUIX_CAR_INFOTAINMENT) += car_infotainment/
obj-$(CONFIG_AZURE_GUIX_WIDGET_ANIMATION) += widget_animation/

obj-y += display/
obj-y += azure_guix_demo.o
