obj-y += gx_binres_language_count_get.o
obj-y += gx_binres_language_info_load.o
obj-y += gx_binres_language_table_load.o
obj-y += gx_binres_theme_load.o
obj-y += gxe_binres_language_count_get.o
obj-y += gxe_binres_language_info_load.o
obj-y += gxe_binres_language_table_load.o
obj-y += gxe_binres_theme_load.o
