obj-y += core/
obj-y += dev/
obj-y += display/
obj-y += draw/
obj-y += font/
obj-y += indev/
obj-y += osal/
obj-y += layouts/
obj-y += libs/
obj-y += misc/
obj-y += tick/
obj-y += stdlib/
obj-y += others/
obj-y += themes/
obj-y += widgets/

obj-y += lv_init.o
