obj-y += sw/
obj-y += nxp/

obj-y += lv_draw_arc.o
obj-y += lv_draw_image.o
obj-y += lv_draw_buf.o
obj-y += lv_draw_label.o
obj-y += lv_draw_line.o
obj-y += lv_draw_mask.o
obj-y += lv_draw_rect.o
obj-y += lv_draw_triangle.o
obj-y += lv_draw.o
obj-y += lv_image_buf.o
obj-y += lv_image_decoder.o
obj-y += lv_draw_vector.o
