obj-y += sw/

obj-y += lv_draw_arc.o
obj-y += lv_draw_img.o
obj-y += lv_draw_label.o
obj-y += lv_draw_line.o
obj-y += lv_draw_mask.o
obj-y += lv_draw_rect.o
obj-y += lv_draw_triangle.o
obj-y += lv_draw.o
obj-y += lv_img_buf.o
obj-y += lv_img_cache_builtin.o
obj-y += lv_img_cache.o
obj-y += lv_img_decoder.o
