
obj-y += locks.o
obj-y += lights.o
obj-y += weather.o
obj-y += thermostat.o
obj-y += screen_base.o
obj-y += passcode_screen.o
obj-y += controller_base.o
obj-y += guix_home_automation.o
obj-y += demo_guix_home_automation_resources.o
obj-y += demo_guix_home_automation_specifications.o
